#!/bin/bash

buildwebsafecolors () {
cat <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
 <title>Web-safe colors</title>
 <meta name="viewport" content="width=device-width, initial-scale=1">
<style>
div { padding-bottom: 2em; box-shadow: 0 4px 10px #666;}
p { font-family: monospace; margin: 0 auto; text-align: center; background-color: #EEE; color: #222; }
@media only screen and (min-width:768px) {
 body { display: grid; grid-template-columns: repeat(16,1fr); column-gap: 0.5em; row-gap: 0.5em; }
}
@media only screen and (min-width:576px) and (max-width:767px) {
 body { display: grid; grid-template-columns: repeat(8,1fr); column-gap: 0.5em; row-gap: 0.5em; }
}
</style>
</head>
</body>
EOF

for r in 0 1 2 3 4 5 6 7 8 9 a b c d e f ; do
  for g in 0 1 2 3 4 5 6 7 8 9 a b c d e f ; do
    for b in 0 1 2 3 4 5 6 7 8 9 a b c d e f ; do

      echo "<div style='background-color:#$r$g$b'><code>#$r$g$b</code></div>";

    done
  done
done

cat <<EOF

</body>
</html>
EOF

} >> websafecolors.html 2>&1

buildwebsafecolors
